### PR TITLE
Adding devtools directory with instructions to create conda env

### PR DESCRIPTION
**Pull request by dprada**
Adding devtools directory with instructions and dependencies to create the conda env to work with this repo.

### CODE REVIEW

**Comment by casuarioq** [comment]
when I typed this (conda env create -n OpenPocket-Tests -f conda_env.yaml) on the terminal it raised this error: SpecNotFound: Invalid name, try the format: user/package

**Comment by dprada** [comment]
`conda_env.yaml` is a file. You have to type:
```bash
conda env create -n OpenPocket-Tests -f conda_env.yaml
```
in the same directory where the file is (in devtools). Otherwise, you have to give the relative or absolute path the file in the command.

Is this the problem you have?

**Comment by casuarioq** [comment]
I typed exactly the same as you write again. I don't know where devtools is: I tried to find it by typing the command which devtools, but it didn't generate any message. I don't know if have to do the second one option. I typed that standing on the base enviroment.

**Comment by dprada** [comment]
This is a Pull Request and the notes in this page are related with the PR. This means that you have to review the PR and Merge the pull request to add my changes to the repository:

1- As you can see in the top-right part of this page, you were proposed as a reviewer. This means that you have to "do a review". Go to the label "Files changed", look at the changes and do your review (you have to either accept the changes, deny them, or comment with your approval pending).
2- Once the reviewers accepted the PR, the changes can be finally merged. This is done by the "Merge pull request" green button on this page.

Now, the changes are already in the 'main' branch of this UIBCDF repository. Go to the GitHub webpage of your fork and fetch these changes in your 'main' branch. As the last step, in the local clone of your fork (in your machine), pull the changes (`git pull`). At this point, you already have the devtools directory in your computer.

**Review by casuarioq — APPROVED** [review]

**Comment by casuarioq** [comment]
It did't work, I have the same error, maybe I made a mistake.

**Pull request merged**
